### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by Travisivart** [joshfraser/robinhood-to-csv#1]
Using Python 2.7.11 on Windows 10 I get the following error after entering my username and password:

Traceback (most recent call last):
  File "D:\robinhood-to-csv\csv-export.py", line 32, in <module>
    for key, value in enumerate(executions[0]):
IndexError: list index out of range

**Comment by joshfraser** [comment]
Thanks for the heads up.  I think this should be fixed now.  Mind trying it again to confirm?

I didn't have any queued orders when I wrote the script so I missed the fact that queued orders are returned in a different structure from executed orders.

**Comment by Travisivart** [comment]
No problem.
I gave it another try and was able to get past the first error but I am now getting another new error which I've added as Issue #2.

**Comment by joshfraser** [comment]
Hmm.  Mind pulling the latest version and running it with the debug flag?  Then email me the debug.json file that is generated.

python csv-export.py --debug

**Comment by Travisivart** [comment]
Here you are!

I had to rename the file to .txt for Github to accept it.

Just a couple of thoughts, I have several Canceled orders in my order history as well as undeclared deposits; not sure if those could be causing the issue.

[debug.json.txt](https://github.com/joshfraser/robinhood-to-csv/files/88341/debug.json.txt)
