### ISSUE TITLE
Not compatible with Python 2.7

### ISSUE THREAD

**Issue by hekevintran** [joshfraser/robinhood-to-csv#14]
Your readme states that this is compatible with Python 2.7+, but I found that it is not.  In the script is `print("Robinhood username:", end=' ')`.  This will fail on 2.7 unless you do an import: `from __future__ import print_function`.

I am running Python 2.7.14

**Comment by joshfraser** [comment]
Sorry, it used to work. Mind sending me a pull request to fix that?

**Comment by umer936** [comment]
Shoot, that was my fault. I had thought that part of print was fine in Python2, but apparently not. I'll PR in a bit.
