### ISSUE TITLE
KeyError: u'settlement_date

### ISSUE THREAD

**Issue by Travisivart** [joshfraser/robinhood-to-csv#2]
Using Python 2.7.11 on Windows 10 I get the following error after entering my username and password:

Traceback (most recent call last):
  File "D:\robinhood-to-csv\csv-export.py", line 63, in <module>
    csv += str(fields[row][key]) + ","
KeyError: u'settlement_date'

**Comment by joshfraser** [comment]
Should be fixed with the latest version.  Thanks for helping me debug.

**Comment by Travisivart** [comment]
Yup, it's all working great now. Thank you!

On Wed, Jan 13, 2016 at 2:26 AM, Josh Fraser <notifications@github.com>
wrote:

> Should be fixed with the latest version. Thanks for helping me debug.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joshfraser/robinhood-to-csv/issues/2#issuecomment-171214557>
> .
>



-- 

*Travis Neely*
Database Programmer Analyst
University of Missouri System
