### ISSUE TITLE
experiencing timeouts?

### ISSUE THREAD

**Issue by kenboslice925** [joshfraser/robinhood-to-csv#31]
After i input my username/password, it appears the API call is made as I am left hanging for a period of 1-2 minutes. After which I will receive this error:

raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='api.robinhood.com', port=443): Max retries exceeded with url: /api-token-auth/ (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0A3456D0>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))

Has anyone experienced this and found a fix? I am wondering if it has something to do with my PC, which is behind a corporate proxy.

**Comment by joshfraser** [comment]
Should be fixed with #36. Feel free to reopen if that's not the case.
