### ISSUE TITLE
Unresolved reference "queded_count"

### ISSUE THREAD

**Issue by AlmightyOatmeal** [joshfraser/robinhood-to-csv#34]
Line 112 in `csv-export.py` ( https://github.com/joshfraser/robinhood-to-csv/blob/master/csv-export.py#L112 ).

Also, there is a mixture of tabs and spaces within `cdv-export.py`.

**Comment by tino-247** [comment]
Fix here: https://github.com/joshfraser/robinhood-to-csv/pull/37
