### ISSUE TITLE
Never prompts for username and password without command line options

### ISSUE THREAD

**Issue by kfollmer24** [joshfraser/robinhood-to-csv#41]
Line 37 - 50 where the conditionals that were looking for empty strings didn't work for me because I didn't specify my username and password on the command line.

The argument parser was looking for empty strings but I had none.

My work around was to remove the conditional prompts and ask for the user name and password as follows (not eloquently):

    username = input("Username: ")
    password = getpass.getpass()
    mfa_code = input("mfa_code: ")

**Comment by yogamurthy** [comment]
Yeah. some issue with latest library.

try this command:
python csv-export.py --username <<your_usename_goes_here>> --password <<yyour_password_goes_here>>

**Comment by utimatu** [comment]
Was this a problem with csv-export or just csv-options-export?
