### ISSUE TITLE
Log-in error

### ISSUE THREAD

**Issue by ysriram1** [joshfraser/robinhood-to-csv#44]
When I am trying to run the csv script, this is what I'm getting:

```
>>> python csv-export.py 

Traceback (most recent call last):
  File "csv-options-export.py", line 52, in <module>
    if logged_in != True and logged_in.get('non_field_errors') == None and logged_in['mfa_required'] == True:
KeyError: 'mfa_required'
```

Any ideas on how I can fix this?

**Comment by codejump** [comment]
https://github.com/joshfraser/robinhood-to-csv/pull/42

Look at the pull request

**Comment by joshfraser** [comment]
Merged in @martinmelin's PR. Let me know if this doesn't fix it.

**Comment by ysriram1** [comment]
Thank you! This fixed the issue for csv-export.py, the csv-options-export.py still gets the same error, but I was able to run the options script by simply updating the code the same way as we did for csv-export.py file.
