### ISSUE TITLE
Unable to login using correct credentials

### ISSUE THREAD

**Issue by maraudr** [joshfraser/robinhood-to-csv#5]
I am unable to login with the csv-export.py script, but I CAN log into robinhood.com using the same credentials. I am certain that I am typing everything correctly!

**Comment by joshfraser** [comment]
Do you have special characters in your password by any chance?  There's a known bug around passwords not being encoded correctly.  It's on my todo list to fix, but changing to an alphanumeric password should fix it in the meantime.

**Comment by maraudr** [comment]
Yes I do. Thanks for the heads up!

**Comment by joshfraser** [comment]
Fixed this was the latest version

**Comment by matthewkooshad** [comment]
@joshfraser did you ever fix the special character allowance in password? i'm facing the same issue as OP.
