### ISSUE TITLE
Getting this error when I try to run either csv-export.py or csv-options-export.py

### ISSUE THREAD

**Issue by j10c3y25** [joshfraser/robinhood-to-csv#54]
Robinhood username: Traceback (most recent call last):
  File "csv-export.py", line 41, in <module>
    logged_in = collect_login_data(robinhood_obj=robinhood, username=username, password=password, device_token=device_token, mfa_code=mfa_code)
  File "C:\Users\Josh\Desktop\robinhood-to-csv-master\login_data.py", line 20, in collect_login_data
    username = input()
UnboundLocalError: local variable 'input' referenced before assignment

**Comment by efaillac** [comment]
Me as well. Any solution?
