### ISSUE TITLE
Stop asking for a device_token

### ISSUE THREAD

**Issue by joshfraser** [joshfraser/robinhood-to-csv#56]
Our current instructions for manually grabbing a device_token work but are a bit painful. Looks like we can probably just generate a random one:

https://github.com/securient/Robinhood/commit/95d7dbd89cfe6219bbe4494ce75b6755483444fe

If that doesn't work, we should at least be able to grab one from their API instead of having people dig around in the developer console for it.

Posting this here in case someone gets around to fixing this before me.

**Comment by zameerbharwani** [comment]
Working on it now
