### ISSUE TITLE
Getting "Invalid inputs. Please try again." after inputting device token

### ISSUE THREAD

**Issue by Goldbluered** [joshfraser/robinhood-to-csv#57]
I have tried with and without 2 factor authentication, get the same error regardless. Pulling device token out of Chrome without quotation marks, pasting it, get invalid inputs every time.

**Comment by joshfraser** [comment]
Hmm weird. I tested this on my personal account yesterday and it worked fine.

**Comment by Goldbluered** [comment]
Figured it out. Had to manually type password out instead of copy and pasting it. Have a long random password so this was a pain, but I got past the initial invalid inputs.
