### ISSUE TITLE
Fails with Two-Factor Auth

### ISSUE THREAD

**Issue by BAByrne** [joshfraser/robinhood-to-csv#6]
Login fails when two-factor authentication is enabled. I get the message:

> `Invalid username or password.  Try again.`

**Comment by dimo414** [comment]
Looks like this has been fixed upstream: https://github.com/Jamonek/Robinhood/pull/31

**Comment by umer936** [comment]
https://github.com/joshfraser/robinhood-to-csv/pull/11

**Comment by joshfraser** [comment]
Thanks for tackling this, Umer Salman

**Comment by jonchui** [comment]
Hm, i'm still having this on the latest version?
