### ISSUE TITLE
Pull Stocks Watching as Well

### ISSUE THREAD

**Issue by hathawayj** [joshfraser/robinhood-to-csv#7]
Less of an issue.  In the App we can watch stocks.  Is there a way to pull the stocks we are watching as well?

**Comment by inoicouldalwaysturn2u** [comment]
Look up code that uses other data sources like Yahoo Finance. Makes much more sense to do that with those. Robinhood shouldn't be used for that sort of stuff.

**Comment by joshfraser** [comment]
Agreed that there are probably better ways to do this, but feel free to fork this code and use it as a starting point if you'd like.
