### ISSUE TITLE
data = urllib.urlencode(fields) errors with my version of python 3

### ISSUE THREAD

**Issue by hathawayj** [joshfraser/robinhood-to-csv#8]
I fixed it in my script using    data = urllib.parse.urlencode(fields) based on http://stackoverflow.com/questions/28906859/module-has-no-attribute-urlencode

**Comment by umer936** [comment]
This issue can be closed as it was fixed in this commit https://github.com/joshfraser/robinhood-to-csv/commit/1371d4bb4f1c7ffda061e96f23c2dfc05a99da8d
